services:
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  backend:
    image: bengostar/vchat-service:latest
    ports:
      - '8000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}
      - SUPABASE_DB_PWD=${SUPABASE_DB_PWD}
      - SUPABASE_ANON_PUB=$SUPABASE_ANON_PUB}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - PINO_LOG_LEVEL=${PINO_LOG_LEVEL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ADMIN_UI_USERNAME=${ADMIN_UI_USERNAME}
      - ADMIN_UI_PASSWORD=${ADMIN_UI_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    environment:
      - CADDY_EMAIL=${CADDY_EMAIL}
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - CADDY_PROXY_ADDRESS=backend:8000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    privileged: true
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    ports:
      - '12345:12345'
    command: >
      run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data:
  caddy_data:
    external: true
  caddy_config:
