version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - '8000'
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.75'
          memory: 1G

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./apps/server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  redis_data:
