version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: server.Dockerfile
      target: server
    ports:
      - '8000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}
      - SUPABASE_DB_PWD=${SUPABASE_DB_PWD}
      - SUPABASE_ANON_PUB=$SUPABASE_ANON_PUB}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - PINO_LOG_LEVEL=${PINO_LOG_LEVEL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ADMIN_UI_USERNAME=${ADMIN_UI_USERNAME}
      - ADMIN_UI_PASSWORD=${ADMIN_UI_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.75'
          memory: 1G

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '443:443'
    volumes:
      - ./apps/server/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      SSL_CERTIFICATE: ${SSL_CERTIFICATE}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY}
      FULL_DOMAIN: ${FULL_DOMAIN}
    entrypoint: ["/docker-entrypoint.sh"]
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  redis_data:
