name: Test + Lint

on:
  workflow_dispatch:
  push:

jobs:
  mono-ci:
    runs-on: ubuntu-latest

    env:
      # Configure redis-memory-server to use pre-built binaries
      REDISMS_DOWNLOAD_MIRROR: https://download.redis.io/redis-stable/
      REDISMS_DISABLE_POSTINSTALL: 1
      MALLOC: libc

    # services:
    #   redis:
    #     image: redis:7-alpine
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm --filter "./packages/*" build

      - name: Web tests + lint
        run: |
          pnpm run web test
          pnpm run web lint

      - name: Server tests + typecheck
        run: |
          pnpm run server test
          pnpm run server typecheck
