name: Test + Lint

on:
  workflow_dispatch:
  push:

jobs:
  mono-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'

      # Add Redis binaries cache
      - name: Cache Redis binaries
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/redis-binaries
          key: ${{ runner.os }}-redis-memory-server-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-redis-memory-server-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm --filter "./packages/*" build

      - name: Web tests + lint
        run: |
          pnpm run web test
          pnpm run web lint

      - name: Server tests + typecheck
        run: |
          pnpm run server test
          pnpm run server typecheck
